# Generated by Django 5.2.7 on 2025-10-27 23:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("currencies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Asset name or description", max_length=200
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash & Bank Accounts"),
                            ("INVESTMENT", "Investment Portfolio"),
                            ("REAL_ESTATE", "Real Estate"),
                            ("VEHICLE", "Vehicle"),
                            ("PRECIOUS_METALS", "Precious Metals"),
                            ("CRYPTOCURRENCY", "Cryptocurrency"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Category of asset",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current value of the asset",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        help_text="Bank, brokerage, or institution name",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="Masked account number (e.g., ****1234)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this asset",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this asset is currently active (soft delete)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_valued_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When value was last updated"
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        help_text="Currency in which value is denominated",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="currencies.currency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of this asset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Value at this point in time",
                        max_digits=15,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of this record"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual Entry"),
                            ("STATEMENT_UPLOAD", "Statement Upload"),
                            ("API_SYNC", "API Sync"),
                        ],
                        default="MANUAL",
                        help_text="How this value was recorded",
                        max_length=20,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset this history belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="assets.asset",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        help_text="Currency of the value",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_history",
                        to="currencies.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset History",
                "verbose_name_plural": "Asset Histories",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["user", "asset_type", "is_active"],
                name="assets_asse_user_id_02d69c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["user", "is_active", "-updated_at"],
                name="assets_asse_user_id_a8707e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assethistory",
            index=models.Index(
                fields=["asset", "-recorded_at"], name="assets_asse_asset_i_a1ae76_idx"
            ),
        ),
    ]
