# Generated by Django 5.2.7 on 2025-10-27 23:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="ISO 4217 currency code (e.g., USD, EUR, INR)",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the currency", max_length=100
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Currency symbol (e.g., $, €, ₹)", max_length=10
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this currency is currently supported",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Exchange rate (1 from_currency = rate * to_currency)",
                        max_digits=20,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date for which this rate is valid",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="exchangerate-api",
                        help_text="API source that provided this rate",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_currency",
                    models.ForeignKey(
                        help_text="Source currency",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates_from",
                        to="currencies.currency",
                    ),
                ),
                (
                    "to_currency",
                    models.ForeignKey(
                        help_text="Target currency",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates_to",
                        to="currencies.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "ordering": ["-date", "from_currency", "to_currency"],
                "indexes": [
                    models.Index(
                        fields=["from_currency", "to_currency", "-date"],
                        name="currencies__from_cu_c1a64b_idx",
                    )
                ],
                "unique_together": {("from_currency", "to_currency", "date")},
            },
        ),
    ]
