# Generated by Django 5.2.7 on 2025-11-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="exchangerate",
            index=models.Index(
                fields=["from_currency", "to_currency", "date"],
                name="currencies__from_cu_7d8f00_idx",
            ),
        ),
    ]
