# Generated by Django 5.2.7 on 2025-10-27 23:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("currencies", "0001_initial"),
        ("households", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NetWorthSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_assets",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total value of all assets at snapshot time",
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_liabilities",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total value of all liabilities at snapshot time",
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "net_worth",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Calculated net worth (assets - liabilities)",
                        max_digits=18,
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(db_index=True, help_text="Date of this snapshot"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "currency",
                    models.ForeignKey(
                        help_text="Currency in which values are expressed (user's home currency)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="networth_snapshots",
                        to="currencies.currency",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        help_text="Household this snapshot belongs to (null for individual snapshots)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="networth_snapshots",
                        to="households.household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User this snapshot belongs to (null for household snapshots)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="networth_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Net Worth Snapshot",
                "verbose_name_plural": "Net Worth Snapshots",
                "ordering": ["-snapshot_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-snapshot_date"],
                        name="networth_ne_user_id_c9295d_idx",
                    ),
                    models.Index(
                        fields=["household", "-snapshot_date"],
                        name="networth_ne_househo_8011f4_idx",
                    ),
                ],
                "unique_together": {
                    ("household", "snapshot_date"),
                    ("user", "snapshot_date"),
                },
            },
        ),
    ]
