# Generated by Django 5.2.7 on 2025-10-28 05:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0001_initial"),
        ("networth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networthsnapshot",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Currency in which values are expressed (auto-set to user's home currency if not provided)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="networth_snapshots",
                to="currencies.currency",
            ),
        ),
        migrations.AlterField(
            model_name="networthsnapshot",
            name="net_worth",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Calculated net worth (assets - liabilities) (auto-calculated if not provided)",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="networthsnapshot",
            name="snapshot_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Date of this snapshot (defaults to today if not provided)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="networthsnapshot",
            name="total_assets",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total value of all assets at snapshot time (auto-calculated if not provided)",
                max_digits=18,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="networthsnapshot",
            name="total_liabilities",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total value of all liabilities at snapshot time (auto-calculated if not provided)",
                max_digits=18,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
