# Generated by Django 5.2.7 on 2025-10-27 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatementUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded statement file",
                        upload_to="statements/%Y/%m/%d/",
                    ),
                ),
                (
                    "upload_type",
                    models.CharField(
                        choices=[
                            ("BANK_STATEMENT", "Bank Statement"),
                            ("CREDIT_CARD_STATEMENT", "Credit Card Statement"),
                            ("INVESTMENT_STATEMENT", "Investment Statement"),
                            ("LOAN_STATEMENT", "Loan Statement"),
                            ("PROPERTY_VALUATION", "Property Valuation"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of financial statement",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("REVIEWED", "Reviewed & Confirmed"),
                        ],
                        default="PENDING",
                        help_text="Processing status",
                        max_length=20,
                    ),
                ),
                (
                    "parsed_data",
                    models.JSONField(
                        blank=True,
                        help_text="JSON data extracted from statement by LLM",
                        null=True,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Confidence score of parsing (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When file was uploaded"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When processing completed", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if processing failed",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who uploaded the statement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Statement Upload",
                "verbose_name_plural": "Statement Uploads",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-uploaded_at"],
                        name="reports_sta_user_id_3a3d3e_idx",
                    ),
                    models.Index(
                        fields=["status", "-uploaded_at"],
                        name="reports_sta_status_c16690_idx",
                    ),
                ],
            },
        ),
    ]
